import React, { useState, useEffect } from 'react';
import API from '../services/api';
import LoadingSpinner from '../components/LoadingSpinner';
import { FaChartBar } from 'react-icons/fa';

const AdminReportsPage = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const res = await API.get('/admin/reports');
        setReports(res.data.reports || []);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchReports();
  }, []);

  if (loading) return <LoadingSpinner message="Loading System Audit Reports..." />;

  return (
    <div className="container py-3">
      <div className="d-flex align-items-center gap-3 mb-4">
        <div className="p-3 rounded-circle bg-warning-subtle text-warning">
          <FaChartBar size={24} />
        </div>
        <div>
          <h2 className="fw-bold mb-0">System Audit & Reports</h2>
          <p className="text-muted small mb-0">Review batch analytics logs created by Placement Officers</p>
        </div>
      </div>

      <div className="glass-card p-4">
        <h5 className="fw-bold mb-3">Report Archives ({reports.length})</h5>

        {reports.length === 0 ? (
          <p className="text-muted small text-center py-4">No reports found in the system log.</p>
        ) : (
          <div className="d-flex flex-column gap-3">
            {reports.map((rep) => (
              <div key={rep._id} className="p-4 rounded-3 border border-secondary border-opacity-10 bg-body-tertiary">
                <div className="d-flex justify-content-between align-items-center mb-2">
                  <h5 className="fw-bold mb-0">{rep.title}</h5>
                  <span className="text-muted small">{new Date(rep.generatedDate).toLocaleDateString()}</span>
                </div>
                <p className="text-muted small mb-3">Generated By: {rep.generatedBy?.name || 'Officer'}</p>

                <div className="row g-2 text-center">
                  <div className="col-4">
                    <div className="p-2 rounded glass-card">
                      <span className="text-muted small d-block">Students</span>
                      <strong>{rep.metrics?.totalStudents || 0}</strong>
                    </div>
                  </div>
                  <div className="col-4">
                    <div className="p-2 rounded glass-card">
                      <span className="text-muted small d-block">Avg Score</span>
                      <strong className="text-primary">{rep.metrics?.avgReadinessScore || 0}%</strong>
                    </div>
                  </div>
                  <div className="col-4">
                    <div className="p-2 rounded glass-card">
                      <span className="text-muted small d-block">Eligible</span>
                      <strong className="text-success">{rep.metrics?.placedEligibleCount || 0}</strong>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminReportsPage;
