import React, { useState, useEffect } from 'react';
import API from '../services/api';
import LoadingSpinner from '../components/LoadingSpinner';
import ToastAlert from '../components/ToastAlert';
import { FaChartBar, FaDownload, FaPlusCircle } from 'react-icons/fa';

const OfficerReportsPage = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [msg, setMsg] = useState({ text: '', type: '' });

  const fetchReports = async () => {
    try {
      const res = await API.get('/officer/reports');
      setReports(res.data.reports || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerateReport = async () => {
    setGenerating(true);
    setMsg({ text: '', type: '' });

    try {
      const res = await API.post('/officer/reports');
      setMsg({ text: 'Batch placement analytics report generated!', type: 'success' });
      fetchReports();
    } catch (err) {
      setMsg({ text: err.response?.data?.message || 'Failed to generate report.', type: 'danger' });
    } finally {
      setGenerating(false);
    }
  };

  const downloadReport = async (report) => {
    let detailedReport = report;
    try {
      const response = await API.get(`/officer/reports/${report._id}/details`);
      detailedReport = response.data.report;
    } catch (err) {
      setMsg({ text: err.response?.data?.message || 'Unable to load detailed report data.', type: 'danger' });
      return;
    }
    const rows = [
      ['Placement Readiness Batch Report'],
      ['Report Title', detailedReport.title],
      ['Generated On', new Date(detailedReport.generatedDate).toLocaleString()],
      ['Generated By', detailedReport.generatedBy?.name || 'Placement Officer'],
      [],
      ['Metric', 'Value'],
      ['Total Students Analyzed', detailedReport.metrics?.totalStudents || 0],
      ['Batch Average Readiness Score', `${detailedReport.metrics?.avgReadinessScore || 0} / 100`],
      ['Core Drive Eligible Candidates', detailedReport.metrics?.placedEligibleCount || 0],
      [],
      ['Top Skills', (detailedReport.metrics?.topSkills || []).join(', ') || 'Not available'],
      [],
      ['Detailed Student Performance'],
      ['Student Name', 'Email', 'Department', 'CGPA', 'Backlogs', 'Readiness Score', 'Performance Category', 'CGPA Score /20', 'Skills Score /20', 'Projects Score /20', 'Certifications Score /15', 'Internships Score /10', 'Quiz Score /15'],
      ...(detailedReport.studentSnapshots?.length ? detailedReport.studentSnapshots.map((student) => [
        student.name, student.email, student.department, student.cgpa, student.backlogs,
        `${student.readinessScore} / 100`, student.category, student.cgpaScore, student.skillScore,
        student.projectScore, student.certScore, student.internshipScore, student.quizScore
      ]) : [['No student records are available for this report.']])
    ];
    const csv = rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n');
    const file = new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(file);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${detailedReport.title.replace(/[^a-z0-9]+/gi, '-').replace(/(^-|-$)/g, '').toLowerCase()}.csv`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  if (loading) return <LoadingSpinner message="Loading Reports & Analytics..." />;

  return (
    <div className="container py-3">
      <div className="d-flex align-items-center justify-content-between mb-4">
        <div className="d-flex align-items-center gap-3">
          <div className="p-3 rounded-circle bg-warning-subtle text-warning">
            <FaChartBar size={24} />
          </div>
          <div>
            <h2 className="fw-bold mb-0">Placement Batch Reports & Analytics</h2>
            <p className="text-muted small mb-0">Synthesize batch readiness statistics and company eligibility logs</p>
          </div>
        </div>

        <button 
          onClick={handleGenerateReport} 
          className="btn btn-brand rounded-3 d-flex align-items-center gap-2"
          disabled={generating}
        >
          <FaPlusCircle /> {generating ? 'Analyzing Batch...' : 'Generate New Analytics Report'}
        </button>
      </div>

      <ToastAlert message={msg.text} type={msg.type} onClose={() => setMsg({ text: '', type: '' })} />

      <div className="row g-4">
        <div className="col-12">
          <div className="glass-card p-4">
            <h5 className="fw-bold mb-3">Generated Reports Log ({reports.length})</h5>

            {reports.length === 0 ? (
              <p className="text-muted small py-3 text-center">No batch reports generated yet. Click 'Generate New Analytics Report' to create one.</p>
            ) : (
              <div className="d-flex flex-column gap-3">
                {reports.map((rep) => (
                  <div key={rep._id} className="p-4 rounded-3 border border-secondary border-opacity-10 bg-body-tertiary">
                    <div className="d-flex justify-content-between align-items-center mb-3">
                      <div>
                        <h5 className="fw-bold mb-1">{rep.title}</h5>
                        <span className="text-muted small">
                          Generated on: {new Date(rep.generatedDate).toLocaleString()} • By {rep.generatedBy?.name || 'Placement Officer'}
                        </span>
                      </div>
                      <div className="d-flex align-items-center gap-2">
                        <span className="badge bg-primary-subtle text-primary border border-primary-subtle px-3 py-2">Official Audit Report</span>
                        <button type="button" onClick={() => downloadReport(rep)} className="btn btn-sm btn-outline-brand rounded-3 d-flex align-items-center gap-1"><FaDownload /> Download Report</button>
                      </div>
                    </div>

                    <div className="row g-3 text-center">
                      <div className="col-md-4">
                        <div className="p-3 rounded-3 glass-card">
                          <span className="text-muted small d-block">Total Students Analyzed</span>
                          <strong className="fs-4">{rep.metrics?.totalStudents || 0}</strong>
                        </div>
                      </div>
                      <div className="col-md-4">
                        <div className="p-3 rounded-3 glass-card">
                          <span className="text-muted small d-block">Batch Avg Readiness Score</span>
                          <strong className="fs-4 text-primary">{rep.metrics?.avgReadinessScore || 0} / 100</strong>
                        </div>
                      </div>
                      <div className="col-md-4">
                        <div className="p-3 rounded-3 glass-card">
                          <span className="text-muted small d-block">Core Drive Eligible Candidates</span>
                          <strong className="fs-4 text-success">{rep.metrics?.placedEligibleCount || 0}</strong>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default OfficerReportsPage;
